// =====================================================================================
// SECTION 1 — CONFIG / TUNING. Every balance number in the game lives in T.
// =====================================================================================
const T = {
  sim: { hz: 120, maxSteps: 8 },
  view: { height: 500, lead: .22, leadMax: 95, follow: 11, zoomIntense: .06, maxPx: 2.4e6 },
  tile: 32,
  player: {
    r: 9, speed: 232, accel: 3000, friction: 20, dashSpeed: 900, dashTime: .15, dashCd: .72, dashIframe: .2,
    hitIframe: .8, grazeR: 20, grazeSlow: .32, grazeSlowScale: .32, grazeAmmo: .35, grazeCharge: .12,
    pickupR: 90, swapTime: .25, comboTime: 2.6,
  },
  fx: {
    hitstopKill: .028, hitstopHeavy: .05, hitstopCap: .09, traumaDecay: 1.5, maxTrauma: 1, shakePx: 16, shakeRot: .045,
    maxParticles: 6000, decalFade: .035, dmgNumbers: 40, abberation: .006, lowHp: .3, maxLights: 160,
  },
  // status effects (base values; upgrades add on top)
  ST: {
    burnDps: 8, burnDur: 3, chillMax: 100, freezeDur: 1.5, chillDecay: 14, chillSlow: .5, shockDmg: 15, shockJumps: 3,
    shockRange: 140, shockFall: .85, poisonDps: 3, poisonMax: 20, poisonDecay: 1.6, critBase: .05, critMul: 2,
    explodeR: 40, explodeDmg: .4, missileDmg: 45, seekerDmg: 20, shardDmg: 12, droneDmg: 10, droneRate: 3,
    orbitalDmg: 15, sentryDmg: 20, teslaDmg: 30, teslaCd: 1.5, nukeDmg: 250, nukeKills: 25, bombDmg: 70,
    dashFireDur: 2.5, burnExplodeR: 60, ghostDur: 8, barrierCd: 10, impaleDmg: 40, capacitorN: 10,
  },
  // ---------------------------------------------------------------- weapons
  // k: kind | dmg per projectile | rate shots/s | mag | rel reload s | spr spread rad | cnt pellets | spd u/s
  // life s | sz radius | kb knockback | rec recoil px | shk trauma | snd | sh bullet shape
  W: {
    sidearm: { n: 'Sidearm', k: 'gun', d: 'Reliable semi-precise pistol.', dmg: 17, rate: 6, mag: 14, rel: .8, spr: .035, cnt: 1, spd: 720, life: .8, sz: 3, kb: 90, rec: 3, shk: .1, snd: 'pistol', sh: 'bolt' },
    scatter: { n: 'Scattergun', k: 'gun', d: 'Eight pellets of close-range devastation.', dmg: 9, rate: 1.7, mag: 5, rel: 1.1, spr: .34, cnt: 8, spd: 640, spdVar: .18, life: .36, sz: 2.6, kb: 170, rec: 9, shk: .3, snd: 'shotgun', sh: 'pellet', drag: 2.2 },
    stinger: { n: 'Stinger SMG', k: 'gun', d: 'Hose of light rounds.', dmg: 8, rate: 15, mag: 36, rel: 1.15, spr: .15, cnt: 1, spd: 700, life: .55, sz: 2.4, kb: 35, rec: 1.5, shk: .05, snd: 'smg', sh: 'bolt' },
    minigun: { n: 'Shredder', k: 'gun', d: 'Spins up to a storm. Slows you while firing.', dmg: 9, rate: 24, rateMin: 5, spin: .9, mag: 180, rel: 2.2, spr: .13, cnt: 1, spd: 760, life: .6, sz: 2.6, kb: 40, rec: 1.2, shk: .05, snd: 'minigun', sh: 'bolt', slow: .62 },
    rocket: { n: 'Rocketeer', k: 'gun', d: 'Accelerating rockets. Big boom.', dmg: 30, rate: 1.35, mag: 4, rel: 1.5, spr: .02, cnt: 1, spd: 260, acc: 1300, maxSpd: 820, life: 1.2, sz: 5, kb: 60, rec: 8, shk: .25, snd: 'rocket', sh: 'rocket', exp: 72, expD: 60 },
    rail: { n: 'Railgun', k: 'rail', d: 'Hitscan slug that pierces everything.', dmg: 115, rate: .9, mag: 3, rel: 1.4, spr: 0, range: 1400, kb: 220, rec: 14, shk: .45, snd: 'rail' },
    beam: { n: 'Prism Beam', k: 'beam', d: 'Continuous beam that ramps up. Overheats.', dmg: 6, rate: 20, mag: 100, rel: 1.6, heat: 3.2, ramp: 1.6, rampMul: .6, range: 400, kb: 12, rec: .5, shk: .02, snd: 'beam' },
    arc: { n: 'Arc Caster', k: 'arc', d: 'Lightning that leaps between enemies.', dmg: 26, rate: 3.6, mag: 18, rel: 1.2, range: 290, cone: .55, chain: 3, fall: .8, kb: 50, rec: 2, shk: .1, snd: 'arc' },
    disc: { n: 'Disc Thrower', k: 'gun', d: 'Razor discs that pierce and return.', dmg: 21, rate: 2.6, mag: 6, rel: 1.2, spr: .03, cnt: 1, spd: 600, life: 1.3, sz: 6, kb: 70, rec: 4, shk: .1, snd: 'disc', sh: 'disc', pierce: 99, ret: .42 },
    flamer: { n: 'Flamethrower', k: 'gun', d: 'Short-range cone of burning plasma.', dmg: 4.5, rate: 32, mag: 120, rel: 1.6, spr: .26, cnt: 1, spd: 430, spdVar: .25, life: .34, sz: 6, kb: 8, rec: .6, shk: .015, snd: 'flame', sh: 'flame', pierce: 99, burn: .5, drag: 2.5 },
    bow: { n: 'Charge Bow', k: 'bow', d: 'Hold to draw. Full draw pierces and always crits.', dmg: 24, dmgMax: 120, charge: .75, rate: 3, mag: 99, rel: .1, spr: .0, spd: 520, spdMax: 1200, life: .9, sz: 3.5, kb: 160, rec: 6, shk: .22, snd: 'bow', sh: 'arrow' },
    orbit: { n: 'Orbit Blades', k: 'orbit', d: 'Blades circle you; fire to fling one out.', dmg: 20, rate: 3.2, mag: 4, rel: 1.2, spd: 560, life: .5, sz: 7, kb: 120, rec: 3, shk: .08, snd: 'blade', sh: 'blade', orbitR: 46, orbitSpd: 6.5, orbitDmg: 12, pierce: 99, ret: .5 },
    mines: { n: 'Mine Layer', k: 'gun', d: 'Lobs proximity mines that arm and detonate.', dmg: 10, rate: 2.2, mag: 6, rel: 1.4, spr: .05, cnt: 1, spd: 520, life: .55, sz: 5, kb: 30, rec: 4, shk: .08, snd: 'mine', sh: 'mine', drag: 5, mine: 1, exp: 78, expD: 75, prox: 52, arm: .3, mineLife: 14 },
  },
  // ---------------------------------------------------------------- enemies
  // hp spd r col | dmg contact/bullet | b brain | cost threat | plus brain params
  E: {
    mite: { n: 'Mite', hp: 14, spd: 168, r: 7, col: '#ff4d6d', dmg: 8, b: 'swarm', cost: 1, lunge: 430, wind: .38, cd: 1.2, d: 'Swarmers. Stage in packs, then rush together.' },
    gunner: { n: 'Gunner', hp: 40, spd: 98, r: 10, col: '#ffa53a', dmg: 11, b: 'gunner', cost: 3, range: 250, bspd: 235, burst: 3, wind: .5, cd: 2.1, d: 'Takes cover, leads its shots, flanks when ordered.' },
    ram: { n: 'Ram', hp: 70, spd: 88, r: 13, col: '#ff6a3a', dmg: 22, b: 'charger', cost: 4, wind: .75, cspd: 580, cdur: .7, cd: 2.6, d: 'Telegraphs a line, then charges. Stuns itself on walls.' },
    bulwark: { n: 'Bulwark', hp: 125, spd: 58, r: 14, col: '#58a8ff', dmg: 12, b: 'shield', cost: 5, arc: 1.05, bspd: 190, wind: .7, cd: 2.4, d: 'Frontal shield blocks bullets. Flank it.' },
    lancer: { n: 'Lancer', hp: 34, spd: 86, r: 10, col: '#ff3df0', dmg: 24, b: 'sniper', cost: 5, range: 470, bspd: 860, wind: 1.15, cd: 2.4, d: 'Seeks long sightlines. Laser sight before every shot.' },
    lobber: { n: 'Lobber', hp: 46, spd: 70, r: 11, col: '#c8ff3a', dmg: 20, b: 'mortar', cost: 4, range: 400, flight: 1.05, blast: 52, shells: 3, wind: .55, cd: 3.2, d: 'Mortar. Shells land on marked circles — flushes campers.' },
    brood: { n: 'Brood', hp: 72, spd: 60, r: 13, col: '#b05cff', dmg: 10, b: 'summoner', cost: 6, cd: 5, spawn: 3, maxKids: 9, wind: .9, d: 'Hatches Mites. Keeps its distance.' },
    phantom: { n: 'Phantom', hp: 46, spd: 125, r: 10, col: '#9d7bff', dmg: 18, b: 'assassin', cost: 5, cd: 4.2, mark: .7, slashR: 38, d: 'Blinks behind you. Watch for the marker.' },
    tick: { n: 'Tick', hp: 16, spd: 178, r: 8, col: '#ffdf3a', dmg: 26, b: 'bomber', cost: 2, fuse: .7, blast: 72, trig: 62, d: 'Kamikaze. Its blast hurts everyone.' },
    mender: { n: 'Mender', hp: 52, spd: 88, r: 10, col: '#3dffa8', dmg: 9, b: 'healer', cost: 5, heal: 14, range: 210, d: 'Heals allies from behind the front line. Priority target.' },
    warden: { n: 'Warden', hp: 85, spd: 70, r: 12, col: '#ffd23a', dmg: 11, b: 'buffer', cost: 5, aura: 150, buffSpd: .35, buffDef: .3, bspd: 140, cd: 2.8, wind: .6, d: 'Aura hastes and armors nearby allies.' },
    delver: { n: 'Delver', hp: 62, spd: 150, r: 12, col: '#d08a4a', dmg: 14, b: 'burrower', cost: 5, emerge: .85, ring: 12, bspd: 170, cd: 3.4, d: 'Burrows toward you; a ring marks where it erupts.' },
    spire: { n: 'Spire', hp: 115, spd: 0, r: 14, col: '#ff5ab4', dmg: 10, b: 'turret', cost: 5, bspd: 140, rate: 9, d: 'Stationary bullet-hell emitter.' },
    mimic: { n: 'Mimic', hp: 160, spd: 135, r: 14, col: '#ffcf5a', dmg: 16, b: 'mimic', cost: 0, bspd: 200, wind: .5, cd: 1.8, d: 'That chest has teeth.' },
    gel: { n: 'Gel', hp: 64, spd: 72, r: 15, col: '#7dff3a', dmg: 12, b: 'gel', cost: 3, hop: 330, wind: .45, cd: 1.6, d: 'Hops at you and splits when popped.' },
    wisp: { n: 'Wisp', hp: 22, spd: 150, r: 8, col: '#e05cff', dmg: 9, b: 'wisp', cost: 2, fly: 1, range: 190, bspd: 230, wind: .4, cd: 1.8, d: 'Flying drone. Ignores cover, orbits, harasses.' },
    jugg: { n: 'Juggernaut', hp: 270, spd: 55, r: 19, col: '#ff3b3b', dmg: 28, b: 'brute', cost: 9, armor: 3, slamR: 95, wind: .95, cd: 3, bspd: 160, d: 'Armored. Ground slam + shockwave.' },
  },
  elite: {
    hpMul: 2.6, rMul: 1.22, gold: 4, chance: .08, mods: ['vampiric', 'hasted', 'splitting', 'shielded', 'volatile', 'reflective'],
    vampiric: { heal: .35, col: '#ff2244' }, hasted: { spd: .45, rate: .35, col: '#ffe23a' }, splitting: { n: 2, hp: .35, col: '#7dff3a' },
    shielded: { frac: .45, regen: 4, col: '#58a8ff' }, volatile: { r: 90, dmg: 24, fuse: .8, col: '#ff8a2b' }, reflective: { every: 4.5, dur: 1.4, col: '#ffffff' },
    names: { vampiric: 'Vampiric', hasted: 'Hasted', splitting: 'Splitting', shielded: 'Shielded', volatile: 'Volatile', reflective: 'Reflective' },
  },
  boss: {
    prism: { n: 'PRISM WARDEN', t: 'Keeper of the Neon Ruins', hp: 3000, r: 40, col: '#ff2bd6' },
    forge: { n: 'CRYO FORGEMASTER', t: 'Tyrant of the Frozen Foundry', hp: 4300, r: 44, col: '#6fd8ff' },
    bloom: { n: 'MOTHER BLOOM', t: 'Heart of the Undergrowth', hp: 5400, r: 46, col: '#7dff3a' },
    arch: { n: 'THE ARCHITECT', t: 'Mind of the Core', hp: 7200, r: 42, col: '#ffcc33' },
  },
  // ---------------------------------------------------------------- AI
  ai: {
    thinkHz: 5, losHz: 6, tokensRanged: [3, 4, 5, 6], tokensMelee: [2, 3, 3, 4], accuracy: [.55, .68, .78, .86], accHeat: .025,
    sepR: 1.9, sepW: 1.6, avoidW: 1.2, cohW: .15, rushPack: 4, rushWait: 3.2, pathBudget: 4, flankAng: 1.6,
    turtleSpd: 55, kiteSpd: 160, adaptRate: .25, ffCheck: 1, maxAttackersNear: 6,
  },
  director: {
    budget: 16, perLayer: 3.5, biomeMul: 1.5, eliteMul: 1.5, waveFrac: .34, maxAlive: [16, 22, 28, 34], peakStress: .72,
    relaxStress: .3, relaxTime: 3.2, peakTime: 4.5, spawnDelay: .9, minSpawnDist: 260, stressDmg: .012, stressDecay: .09,
    challengeTime: 40,
  },
  // ---------------------------------------------------------------- biomes
  BIO: [
    { id: 'neon', n: 'NEON RUINS', bg: '#07020f', floor: '#120a22', floor2: '#170d2c', grid: '#2a1450', wall: '#1d1036', top: '#2c1850', edge: '#ff2bd6', acc: '#22e8ff', amb: '#8274b8',
      haz: ['elec', 'spike'], pool: { mite: 5, gunner: 4, ram: 2, tick: 2, wisp: 2, bulwark: 1, lancer: 1, spire: 1 }, boss: 'prism' },
    { id: 'frost', n: 'FROZEN FOUNDRY', bg: '#020a12', floor: '#0b1824', floor2: '#0e1e2d', grid: '#143048', wall: '#11263a', top: '#1b3a55', edge: '#6fd8ff', acc: '#ff8a2b', amb: '#7090b0',
      haz: ['ice', 'lava', 'spike'], pool: { mite: 3, gunner: 3, ram: 2, tick: 2, wisp: 1, bulwark: 2, lancer: 2, lobber: 3, mender: 2, delver: 2, jugg: 1, spire: 1 }, boss: 'forge' },
    { id: 'toxic', n: 'TOXIC UNDERGROWTH', bg: '#030a04', floor: '#0b170c', floor2: '#0f1e10', grid: '#173a1a', wall: '#13261a', top: '#1e3b26', edge: '#7dff3a', acc: '#ffe23a', amb: '#76946a',
      haz: ['acid', 'spike'], pool: { mite: 3, gunner: 3, ram: 1, tick: 2, wisp: 2, bulwark: 1, lancer: 2, lobber: 2, mender: 2, delver: 1, jugg: 1, gel: 4, brood: 2, warden: 2, phantom: 2, spire: 1 }, boss: 'bloom' },
    { id: 'core', n: 'THE CORE', bg: '#0f0303', floor: '#1d0808', floor2: '#240a0a', grid: '#401414', wall: '#2a0d0d', top: '#451616', edge: '#ff3b1f', acc: '#ffcc33', amb: '#a8665c',
      haz: ['lava', 'elec', 'spike'], pool: { mite: 3, gunner: 3, ram: 2, tick: 2, wisp: 2, bulwark: 2, lancer: 2, lobber: 2, mender: 2, delver: 2, jugg: 2, gel: 2, brood: 1, warden: 2, phantom: 3, spire: 1 }, boss: 'arch' },
  ],
  haz: {
    lava: { dps: 22, burn: 1 }, elec: { off: 2.6, warn: .85, on: 1.2, dmg: 18 }, spike: { warn: .5, up: .6, dmg: 16, rearm: 1.4 },
    acid: { stacks: 3 }, ice: { friction: .12 },
  },
  map: { layers: 6, minW: 2, maxW: 4,
    w: { combat: 50, elite: 12, shop: 9, treasure: 8, challenge: 7, rest: 7, event: 11 } },
  room: { minW: 30, maxW: 46, minH: 22, maxH: 32, barrels: [1, 4], cover: [2, 6], hazards: [0, 3], coverHp: 60, barrelHp: 20, barrelDmg: 55, barrelR: 82 },
  // ---------------------------------------------------------------- economy
  gold: { enemy: 1.4, elite: 6, room: 12, boss: 80, startGold: 0 },
  price: { rar: [45, 80, 140, 220, 60], heal: 40, weapon: 90, active: 75, reroll: 25 },
  rarityW: [62, 27, 9, 2], luckW: [-8, 4, 3, 1], curseChance: .1,
  rest: { heal: .4, maxHp: 15 },
  // ---------------------------------------------------------------- characters
  CH: {
    kestrel: { n: 'KESTREL', role: 'Vanguard', col: '#22e8ff', hp: 100, spd: 1, w: 'sidearm', ab: 'frag', cd: 6, lock: 0,
      p: 'Perfect dodges refill your magazine and grant +30% damage for 2.5s.', ad: 'Frag Grenade: lob a grenade that explodes for 80 damage.' },
    ember: { n: 'EMBER', role: 'Pyromancer', col: '#ff7a2b', hp: 100, spd: 1, w: 'flamer', ab: 'inferno', cd: 8, lock: 0, up: ['kindling'],
      p: 'Immune to fire and lava. Burn spreads on kill. Burn +25% damage.', ad: 'Inferno Wave: a burning shockwave that knocks enemies back.' },
    volt: { n: 'VOLT', role: 'Stormcaller', col: '#b98bff', hp: 95, spd: 1.03, w: 'arc', ab: 'tesla', cd: 11, lock: 150,
      p: 'Every 5th hit chains lightning. Shock briefly stuns.', ad: 'Tesla Field: a zone that zaps every enemy inside for 5s.' },
    bastion: { n: 'BASTION', role: 'Fortress', col: '#5dff8a', hp: 135, spd: .92, w: 'scatter', ab: 'sentry', cd: 13, lock: 'ach:prism',
      p: '20 regenerating shield. Takes 15% less damage. Heavy knockback.', ad: 'Sentry: deploy a turret that fires for 10s.' },
    wraith: { n: 'WRAITH', role: 'Phantom Blade', col: '#ff4dd2', hp: 80, spd: 1.1, w: 'bow', ab: 'blink', cd: 3.5, lock: 300,
      p: '2 dash charges. Kills refund a dash. +15% crit chance.', ad: 'Phase Blink: teleport to the cursor, slicing through enemies (60 dmg).' },
  },
  ab: { frag: { dmg: 80, r: 85, fuse: .55, range: 300 }, inferno: { dmg: 30, r: 170, kb: 520 }, tesla: { dur: 5, r: 130, dmg: 22, hz: 3 },
    sentry: { dur: 10, dmg: 14, rate: 6 }, blink: { range: 230, dmg: 60 } },
  // actives (Q/E)
  ACT: {
    wipe: { n: 'Null Pulse', cd: 22, d: 'Erase enemy bullets within 280 and knock enemies back.' },
    warp: { n: 'Chrono Field', cd: 30, d: 'Enemies and their bullets move at 40% speed for 4s.', dur: 4, scale: .4 },
    decoy: { n: 'Holo Decoy', cd: 22, d: 'Deploy a decoy that draws enemy attention for 6s.', dur: 6 },
    overdrive: { n: 'Overdrive', cd: 28, d: '+60% fire rate and no reloading for 5s.', dur: 5 },
    hole: { n: 'Singularity', cd: 26, d: 'A black hole at the cursor pulls enemies for 2.5s, then implodes (90 dmg).', dur: 2.5, dmg: 90 },
    flask: { n: 'Nanite Flask', cd: 50, d: 'Heal 25 HP.', heal: 25 },
    aegis: { n: 'Aegis', cd: 24, d: 'Reflect enemy bullets for 2.5s.', dur: 2.5 },
    strike: { n: 'Orbital Strike', cd: 30, d: 'After 0.8s, 6 beams strike around the cursor (65 dmg each).', dmg: 65 },
  },
  // ---------------------------------------------------------------- meta
  meta: {
    weapons: { sidearm: 0, scatter: 0, stinger: 0, rocket: 0, disc: 0, flamer: 0, arc: 0, rail: 120, beam: 150, minigun: 150, bow: 180, orbit: 200, mines: 160 },
    boosts: { vit: { n: 'Vitality', d: '+8 max HP', max: 3, cost: [60, 120, 200] }, fortune: { n: 'Fortune', d: '+1 reroll per run', max: 2, cost: [80, 180] },
      insight: { n: 'Insight', d: '+1 banish per run', max: 2, cost: [80, 180] }, prospect: { n: 'Prospector', d: '+20 starting gold', max: 3, cost: [50, 100, 160] },
      mend: { n: 'Field Medic', d: '+8% rest-site healing', max: 2, cost: [70, 140] } },
    shardsPerRoom: 3, shardsPerBoss: 25, shardsPerKill: .04, winBonus: 60, heatBonus: .12,
  },
  heat: [
    'Enemies have +15% HP', 'Elites appear twice as often', 'Enemy bullets +12% faster', 'Rest sites heal 50% less', 'Enemies deal +20% damage',
    'Directors are relentless: +25% threat budget', 'Bosses gain +25% HP', 'One fewer upgrade choice', 'Enemies are 10% faster', 'No healing from orbs',
  ],
};

// ---------------------------------------------------------------- upgrades: [id, family, rarity(0-3, 4=cursed), name, desc, stats, opts]
// {key} → value, {key%} → value×100 + '%'. Missing keys resolve from T.ST. Picking adds stats into the build B.
const UPG_ROWS = [
  ['kindling', 'fire', 0, 'Kindling', 'Hits have +{burnChance%} chance to <b>Burn</b> ({burnDps} dps for {burnDur}s).', { burnChance: .2 }],
  ['coals', 'fire', 0, 'Hotter Coals', 'Burn deals +{burnAdd} dps.', { burnAdd: 5 }],
  ['cinderstep', 'fire', 1, 'Cinder Step', 'Dashing leaves a fire trail for {dashFireDur}s that deals {dashFire} dps and Burns.', { dashFire: 14 }],
  ['combustion', 'fire', 1, 'Combustion', 'Burning enemies explode on death for {burnExplode} damage.', { burnExplode: 35 }],
  ['firespread', 'fire', 1, 'Spreading Flames', 'Each second, Burn jumps from every burning enemy to {burnSpread} nearby enemy.', { burnSpread: 1 }],
  ['incendiary', 'fire', 2, 'Incendiary Rounds', 'All hits Burn. Burn damage +{burnPct%}.', { burnChance: 1, burnPct: .4 }],
  ['phoenix', 'fire', 3, 'Phoenix Heart', 'Once per room, lethal damage revives you at 40% HP with a fire nova.', { phoenix: 1 }, { lock: 'ach:win', max: 1 }],
  ['chillrounds', 'frost', 0, 'Chill Rounds', 'Hits apply {chill} <b>Chill</b>. At 100 Chill, enemies Freeze for {freezeDur}s.', { chill: 14 }],
  ['deepfreeze', 'frost', 0, 'Deep Freeze', 'Freeze lasts +{freezeAdd}s.', { freezeAdd: 1 }],
  ['shatter', 'frost', 1, 'Shatter', 'Frozen enemies burst into {shatter} ice shards on death ({shardDmg} dmg, Chill).', { shatter: 6 }],
  ['brittle', 'frost', 1, 'Brittle', 'Frozen enemies take +{brittle%} damage.', { brittle: .5 }],
  ['frostnova', 'frost', 1, 'Frost Nova', 'Dashing releases a nova applying {dashFrost} Chill to enemies within 100.', { dashFrost: 60 }],
  ['abszero', 'frost', 2, 'Absolute Zero', 'Hits apply +{chill} Chill. Chilled enemies are slowed twice as much.', { chill: 25, chillSlow: 1 }],
  ['glacial', 'frost', 2, 'Glacial Armor', 'Taking damage freezes all enemies within 140.', { hurtFreeze: 1 }],
  ['static', 'shock', 0, 'Static Charge', 'Hits have +{shockChance%} chance to <b>chain lightning</b> ({shockDmg} dmg, {shockJumps} jumps).', { shockChance: .15 }],
  ['conductive', 'shock', 0, 'Conductivity', 'Chain lightning jumps +{shockAdd} times.', { shockAdd: 2 }],
  ['highvolt', 'shock', 1, 'High Voltage', 'Chain lightning deals +{shockPct%} damage.', { shockPct: .6 }],
  ['stormdash', 'shock', 1, 'Storm Dash', 'Dashing zaps up to {dashShock} enemies within 170 for 25 damage.', { dashShock: 4 }],
  ['tesla', 'shock', 2, 'Tesla Coil', 'Every {teslaCd}s, lightning strikes the nearest enemy within 240 ({teslaDmg} dmg, chains).', { tesla: 1 }],
  ['capacitor', 'shock', 1, 'Capacitor', 'Every {capacitorN}th hit releases a burst that strikes {capacitor} enemies.', { capacitor: 6 }],
  ['ball', 'shock', 2, 'Ball Lightning', 'Every 8th shot launches a ball of lightning that zaps nearby enemies.', { ballLight: 1 }],
  ['venom', 'poison', 0, 'Venom Tips', 'Hits add {poison} <b>Poison</b> stack ({poisonDps} dps per stack, max {poisonMax}).', { poison: 1 }],
  ['virulence', 'poison', 0, 'Virulence', '+{poisonMaxAdd} max Poison stacks and +{poisonDpsAdd} dps per stack.', { poisonMaxAdd: 10, poisonDpsAdd: 1 }],
  ['toxcloud', 'poison', 1, 'Toxic Cloud', 'Poisoned enemies burst into a toxic cloud on death.', { poisonCloud: 1 }],
  ['neuro', 'poison', 1, 'Neurotoxin', 'Enemies with 8+ Poison move 30% slower and deal 25% less damage.', { neuro: 1 }],
  ['corrosion', 'poison', 1, 'Corrosion', 'Poisoned enemies take +{corrode%} damage per stack.', { corrode: .02 }],
  ['acidtrail', 'poison', 1, 'Acid Wake', 'Dashing leaves an acid pool for 3s that poisons enemies.', { dashAcid: 1 }],
  ['pandemic', 'poison', 2, 'Pandemic', 'Hits add +{poison} Poison. Poisoned enemies pass their stacks to neighbours on death.', { poison: 2, poisonSpread: 1 }],
  ['rubber', 'ricochet', 0, 'Rubber Rounds', 'Bullets bounce off walls +{bounce} times.', { bounce: 2 }],
  ['trickshot', 'ricochet', 1, 'Trick Shot', 'Each bounce adds +{bounceDmg%} damage to the bullet.', { bounceDmg: .3 }],
  ['seekbounce', 'ricochet', 1, 'Seeker Bounce', 'Bounced bullets redirect toward the nearest enemy.', { bounceSeek: 1 }],
  ['pinball', 'ricochet', 2, 'Ricochet Chain', 'Bullets ricochet off enemies to {enemyBounce} more targets.', { enemyBounce: 2 }],
  ['superball', 'ricochet', 0, 'Superball', '+{bounce} bounce and +{pspd%} projectile speed.', { bounce: 1, pspd: .15 }],
  ['echowalls', 'ricochet', 1, 'Echo Walls', 'Wall bounces release a shockwave ({bounceNova} dmg).', { bounceNova: 14 }],
  ['ap', 'pierce', 0, 'Armor Piercing', 'Bullets pierce +{pierce} enemy.', { pierce: 1 }],
  ['penetrator', 'pierce', 1, 'Penetrator', '+{pierce} pierce. Each pierce adds +{pierceDmg%} damage.', { pierce: 2, pierceDmg: .15 }],
  ['phase', 'pierce', 2, 'Phase Rounds', 'Bullets pass through walls and cover.', { phase: 1 }],
  ['lance', 'pierce', 1, 'Lance', '+{pspd%} projectile speed and +{pierce} pierce.', { pspd: .35, pierce: 1 }],
  ['impale', 'pierce', 1, 'Impale', 'Bullets that pierce 3 enemies detonate ({impaleDmg} dmg).', { impale: 1 }],
  ['longbarrel', 'pierce', 0, 'Long Barrel', '+{range%} range and +{dmg%} damage.', { range: .3, dmg: .1 }],
  ['frag', 'split', 0, 'Fragmentation', 'On hit, bullets burst into {split} fragments (35% damage).', { split: 2 }],
  ['wallsplit', 'split', 1, 'Wall Splitter', 'Bullets split into {splitWall} on wall impact.', { splitWall: 3 }],
  ['prismatic', 'split', 1, 'Prismatic', '+{extraProj} projectile per shot. {dmg%} damage.', { extraProj: 1, dmg: -.12 }],
  ['fork', 'split', 0, 'Fork', 'Bullets fork into two after travelling 110 units.', { fork: 1 }],
  ['chainreact', 'split', 2, 'Chain Reaction', 'Fragments can split again. +{split} fragment.', { splitDepth: 1, split: 1 }],
  ['clusterkill', 'split', 1, 'Cluster Kill', 'Kills burst into {killSplit} fragments.', { killSplit: 5 }],
  ['guidance', 'homing', 0, 'Guidance Chip', 'Bullets gently home toward enemies.', { homing: 2.5 }],
  ['lockon', 'homing', 1, 'Lock-On', 'Strong homing and +{crit%} crit chance.', { homing: 4, crit: .05 }],
  ['missilepod', 'homing', 1, 'Missile Pod', 'Every 7th shot fires a homing missile ({missileDmg} dmg explosion). Stacks reduce the interval.', { missile: 1 }],
  ['swarm', 'homing', 2, 'Swarm Missiles', 'Missiles launch in volleys of +{missileCount}.', { missileCount: 2 }, { req: 'missile' }],
  ['seekers', 'homing', 1, 'Seeker Swarm', 'Kills launch a homing seeker ({seekerDmg} dmg).', { killSeeker: 1 }],
  ['smartrounds', 'homing', 0, 'Smart Rounds', 'Mild homing and +{pspd%} projectile speed.', { homing: 1.5, pspd: .15 }],
  ['blast', 'explosive', 1, 'Blast Rounds', 'Bullets explode on hit (radius {explodeR}, 40% damage).', { explode: 1 }],
  ['bigbang', 'explosive', 0, 'Bigger Bangs', '+{expRad%} explosion radius.', { expRad: .35 }],
  ['demolition', 'explosive', 0, 'Demolitionist', '+{expDmg%} explosion damage. Explosions shred cover.', { expDmg: .35 }],
  ['volkills', 'explosive', 1, 'Volatile Kills', 'Enemies have {killExplode%} chance to explode on death (50 dmg).', { killExplode: .25 }],
  ['dashbomb', 'explosive', 1, 'Dash Bomb', 'Dashing drops a bomb ({bombDmg} dmg, 0.6s fuse).', { dashBomb: 1 }],
  ['concussion', 'explosive', 0, 'Concussion', 'Explosions stun enemies for {expStun}s.', { expStun: .6 }],
  ['nuke', 'explosive', 3, 'Tactical Nuke', 'Every {nukeKills} kills, a nuke strikes the densest enemy group ({nukeDmg} dmg).', { nuke: 1 }, { lock: 'ach:synergist', max: 1 }],
  ['drone', 'summon', 1, 'Drone Buddy', 'Gain an attack drone ({droneDmg} dmg, {droneRate} shots/s).', { drones: 1 }],
  ['squadron', 'summon', 2, 'Drone Squadron', '+{drones} attack drones.', { drones: 2 }],
  ['overclock', 'summon', 0, 'Overclock', 'Drones, sentries and orbitals attack {droneRate%} faster.', { droneRate: .4 }, { req: 'summonAny' }],
  ['ghosts', 'summon', 1, 'Spectral Allies', 'Kills have {ghosts%} chance to raise a ghost ally for {ghostDur}s.', { ghosts: .15 }],
  ['sentry', 'summon', 1, 'Turret Kit', 'Deploy a sentry turret ({sentryDmg} dmg) at the start of every room.', { sentry: 1 }],
  ['orbitals', 'summon', 0, 'Orbitals', 'Gain {orbitals} orbiting shards ({orbitalDmg} contact dmg).', { orbitals: 2 }],
  ['hivemind', 'summon', 2, 'Hive Mind', 'Drones, sentries and orbitals apply your elemental effects.', { droneElem: 1 }, { req: 'summonAny' }],
  ['keeneye', 'crit', 0, 'Keen Eye', '+{crit%} crit chance.', { crit: .08 }],
  ['lethal', 'crit', 0, 'Lethality', '+{critDmg%} crit damage.', { critDmg: .5 }],
  ['deadeye', 'crit', 1, 'Deadeye', 'The first {reloadCrit} shots after reloading always crit.', { reloadCrit: 3 }],
  ['executioner', 'crit', 1, 'Executioner', 'Hits on enemies below {execute%} HP always crit.', { execute: .2 }],
  ['cascade', 'crit', 1, 'Crit Cascade', 'Crits grant +12% fire rate for 2s (stacks 4×).', { critHaste: 1 }],
  ['weakpoint', 'crit', 2, 'Weakpoint', '+{crit%} crit chance. Crits double status buildup.', { crit: .15, critStatus: 1 }],
  ['focus', 'crit', 1, "Sniper's Focus", '+{farCrit%} crit chance against enemies farther than 260.', { farCrit: .3 }],
  ['boots', 'speed', 0, 'Light Boots', '+{speed%} move speed.', { speed: .12 }],
  ['quickdraw', 'speed', 0, 'Quickdraw', '+{reload%} reload speed and +{rate%} fire rate.', { reload: .25, rate: .08 }],
  ['afterburner', 'speed', 1, 'Afterburner', '-{dashCd%} dash cooldown.', { dashCd: .3 }],
  ['doubledash', 'speed', 2, 'Double Dash', '+{dashCharges} dash charge.', { dashCharges: 1 }],
  ['momentum', 'speed', 1, 'Momentum', 'Up to +{momentum%} damage while moving (builds over 1s).', { momentum: .35 }],
  ['adrenaline', 'speed', 1, 'Adrenaline', 'Perfect dodges refund your dash and grant +30% fire rate for 3s.', { adrenaline: 1 }],
  ['hyper', 'speed', 0, 'Hyperdrive', '+{pspd%} projectile speed and +{speed%} move speed.', { pspd: .15, speed: .06 }],
  ['plating', 'core', 0, 'Reinforced Plating', '+{maxHp} max HP (heals the same).', { maxHp: 25 }],
  ['vamp', 'core', 1, 'Vampiric Rounds', 'Kills heal {killHeal} HP.', { killHeal: 1 }],
  ['barrier', 'core', 1, 'Barrier', 'A barrier blocks one hit, recharging after {barrierCd}s.', { barrier: 1 }, { max: 1 }],
  ['lucky', 'core', 0, 'Lucky Charm', 'Better upgrade rarities and +{gold%} gold.', { luck: 1, gold: .15 }],
  ['secondwind', 'core', 1, 'Second Wind', 'Clearing a room below 40% HP heals {secondWind%} max HP.', { secondWind: .3 }],
  ['bigmag', 'core', 0, 'Extended Mag', '+{mag%} magazine size.', { mag: .4 }],
  ['heavy', 'core', 0, 'Heavy Rounds', '+{dmg%} damage and +{kb%} knockback.', { dmg: .15, kb: .3 }],
  ['glass', 'curse', 4, 'Glass Cannon', '+{dmg%} damage. <span class=bad>-40% max HP.</span>', { dmg: .6, maxHpPct: -.4 }],
  ['bloodpact', 'curse', 4, 'Blood Pact', 'Kills heal {killHeal} HP. +{rate%} fire rate. <span class=bad>All other healing is disabled.</span>', { killHeal: 2, rate: .2, noHeal: 1 }],
  ['berserker', 'curse', 4, 'Berserker', 'Up to +100% damage as your HP drops. <span class=bad>{maxHp} max HP.</span>', { berserk: 1, maxHp: -25 }],
  ['hairtrigger', 'curse', 4, 'Hair Trigger', '+{rate%} fire rate. <span class=bad>+60% spread, -10% damage.</span>', { rate: .5, spread: -.6, dmg: -.1 }],
  ['greed', 'curse', 4, 'Greed', '+{gold%} gold. <span class=bad>Enemies have +25% HP.</span>', { gold: 1, enemyHp: .25 }],
  ['overcharged', 'curse', 4, 'Overcharged Core', '+{dmg%} damage. <span class=bad>Reloading costs {reloadHurt} HP.</span>', { dmg: .4, reloadHurt: 3 }],
  ['rift', 'curse', 4, 'Unstable Rift', 'Each cleared room grants a random upgrade. <span class=bad>Enemies move 15% faster.</span>', { chaos: 1, enemySpd: .15 }],
  ['heavyheart', 'curse', 4, 'Heavy Heart', '+{maxHp} max HP. <span class=bad>-20% move speed, +40% dash cooldown.</span>', { maxHp: 80, speed: -.2, dashCd: -.4 }],
  ['cursedammo', 'curse', 4, 'Cursed Ammo', '+{dmg%} damage. <span class=bad>You take +30% damage.</span>', { dmg: .35, dmgTaken: .3 }],
];
const FAM = {
  fire: { n: 'Fire', c: '#ff7a2b' }, frost: { n: 'Frost', c: '#7fdcff' }, shock: { n: 'Shock', c: '#b98bff' }, poison: { n: 'Poison', c: '#7dff3a' },
  ricochet: { n: 'Ricochet', c: '#ffd23a' }, pierce: { n: 'Pierce', c: '#ff5ab4' }, split: { n: 'Split', c: '#3dffd8' }, homing: { n: 'Homing', c: '#ff9a5a' },
  explosive: { n: 'Explosive', c: '#ff4a3a' }, summon: { n: 'Summon', c: '#5dff8a' }, crit: { n: 'Crit', c: '#ffef7a' }, speed: { n: 'Speed', c: '#6ab8ff' },
  core: { n: 'Core', c: '#c8d4ea' }, curse: { n: 'Cursed', c: '#ff3355' },
};
// synergies: two families with ≥2 picks each → auto-activate
const SYN_ROWS = [
  ['superconductor', 'frost', 'shock', 'Superconductor', 'Chain lightning leaps between frozen enemies without limit and applies 25 Chill.'],
  ['thermal', 'fire', 'frost', 'Thermal Shock', 'Igniting a frozen enemy shatters its ice for a 60 damage burst.'],
  ['napalm', 'fire', 'explosive', 'Napalm', 'Explosions leave burning ground for 3s.'],
  ['plague', 'poison', 'split', 'Plague', 'Fragments apply 2 Poison. Poisoned kills burst into 3 fragments.'],
  ['electrolysis', 'poison', 'shock', 'Electrolysis', 'Lightning applies 3 Poison. Poisoned enemies take +50% lightning damage.'],
  ['pinballwiz', 'ricochet', 'homing', 'Pinball Wizard', 'Bounces home in on enemies. +1 bounce.'],
  ['drill', 'pierce', 'crit', 'Drill Rounds', 'Each pierce adds +25% crit chance to that bullet.'],
  ['cluster', 'split', 'explosive', 'Cluster Munitions', 'Explosions scatter 3 bomblets (15 dmg).'],
  ['swarmai', 'summon', 'homing', 'Swarm Intelligence', 'Drones and sentries fire a homing missile every 3s.'],
  ['wildfire', 'fire', 'speed', 'Wildfire', 'Fire trails are wider. Moving fast gives +40% Burn chance.'],
  ['cryoshards', 'frost', 'split', 'Cryo Shrapnel', 'Fragments apply 30 Chill. Shatter releases twice the shards.'],
  ['stormcaller', 'shock', 'speed', 'Stormcaller', 'Dashing calls 3 lightning strikes (40 dmg) on nearby enemies.'],
  ['assassin', 'crit', 'speed', "Assassin's Rhythm", 'After dashing, your next 3 shots are critical hits.'],
  ['mirrors', 'ricochet', 'split', 'Hall of Mirrors', 'Every wall bounce splits the bullet in two.'],
  ['smartbombs', 'homing', 'explosive', 'Smart Bombs', 'Homing bullets explode with +50% radius. Missiles deal double damage.'],
  ['hive', 'summon', 'poison', 'Hive', 'Summons apply 3 Poison. Poisoned kills may rise as ghost allies (25%).'],
  ['overload', 'shock', 'explosive', 'Overload', 'Every chain lightning jump triggers an explosion (20 dmg).'],
  ['bloodhound', 'crit', 'homing', 'Bloodhound', 'Crits home aggressively and pierce +1.'],
  ['glacier', 'frost', 'pierce', 'Glacier', 'Pierced enemies gain 30 Chill. Piercing bullets deal double damage to frozen enemies.'],
  ['legion', 'summon', 'fire', 'Burning Legion', 'Summons ignite enemies; drone shots explode in flame.'],
  ['venomrounds', 'poison', 'pierce', 'Venom Lance', 'Each pierce adds +2 Poison stacks.'],
  ['kinetic', 'speed', 'ricochet', 'Kinetic Transfer', 'Bullets gain +25% speed and damage per bounce. +1 bounce.'],
  ['detonator', 'crit', 'explosive', 'Detonator', 'Crits explode (radius 45, 50% damage).'],
  ['thunderclap', 'shock', 'crit', 'Thunderclap', 'Crits always chain lightning.'],
];
// achievements: [id, name, desc, unlock text]
const ACH_ROWS = [
  ['kills100', 'First Blood', 'Kill 100 enemies (total).', ''],
  ['kills2000', 'Exterminator', 'Kill 2,000 enemies (total).', ''],
  ['prism', 'Ruin Breaker', 'Defeat the Prism Warden.', 'Unlocks BASTION'],
  ['forge', 'Thaw', 'Defeat the Cryo Forgemaster.', ''],
  ['bloom', 'Weedkiller', 'Defeat Mother Bloom.', ''],
  ['win', 'Shatterline', 'Defeat The Architect.', 'Unlocks Heat + Phoenix Heart'],
  ['synergist', 'Synergist', 'Discover 5 synergies.', 'Unlocks Tactical Nuke'],
  ['syn12', 'Alchemist', 'Discover 12 synergies.', ''],
  ['untouch', 'Untouchable', 'Clear an elite room without taking damage.', ''],
  ['graze50', 'Bullet Dancer', 'Perform 50 perfect dodges in one run.', ''],
  ['combo50', 'Chain Reaction', 'Reach a 50 kill combo.', ''],
  ['rich', 'Tycoon', 'Hold 400 gold at once.', ''],
  ['cursed3', 'Masochist', 'Hold 3 cursed upgrades at once.', ''],
  ['fast', 'Speedrunner', 'Reach The Core in under 14 minutes.', ''],
  ['heat5', 'Overheated', 'Win at Heat 5 or higher.', ''],
  ['allchars', 'Roster', 'Win with 3 different characters.', ''],
];
